name: ecommerce_app
description: Flutter eCommerce app (part of the Complete Flutter Course Bundle)

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: 0.13.1
  intl: 0.19.0
  flutter_layout_grid: 2.0.6
  flutter_rating_bar: 4.0.1
  go_router: 14.1.1
  flutter_riverpod: 2.5.1
  riverpod_annotation: 2.3.5
  rxdart: 0.27.7
  sembast: 3.7.1
  sembast_web: 2.3.0
  path_provider: 2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter    
  flutter_lints: 4.0.0
  mocktail: 1.0.3
  build_runner: 2.4.9
  riverpod_generator: 2.3.6

# Custom app icon. For more info see: https://pub.dev/packages/flutter_launcher_icons
flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path_ios: "assets/app-icon.png"
  image_path_android: "assets/app-icon.png"
  # https://github.com/fluttercommunity/flutter_launcher_icons/issues/144
  adaptive_icon_background: "assets/app-icon-background.png"
  adaptive_icon_foreground: "assets/app-icon-foreground.png"
  
flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  fonts:
    # Used for Golden Image tests
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

  assets:
    # Add all product images
    - assets/products/

